sudo: required

services:
  - docker

script:
  - cp dataactcore/config_example.yml dataactcore/config.yml
  - cp dataactcore/local_config_example.yml dataactcore/local_config.yml
  - cp dataactcore/local_secrets_example.yml dataactcore/local_secrets.yml
  - |
    docker-compose run --rm dataact-broker \
      /bin/sh -c " \
      cd ./dataactcore; sleep 9s; alembic upgrade head; \
      cd ../; flake8; \
      py.test --cov=. --cov-report xml:tests/coverage.xml --junitxml=tests/test-results.xml"
  - docker-compose down
