language: python

python:
  - '3.5'

services:
  - docker

before_script:
  # Get dependencies to report code coverage to code climate
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - cp dataactcore/config_example.yml dataactcore/config.yml  # copy base/default config to be inherited from
  - docker-compose -f docker-compose.integrationtest.yml up -d  # start the database to use in a container

script:
  - pytest tests/unit/* --cov=. --cov-report xml:tests/coverage.xml --junitxml=tests/test-results.xml
  - pytest tests/integration/* --cov=. --cov-append --cov-report term --cov-report xml:tests/coverage.xml --junitxml=tests/test-results.xml

after_script:
  - docker-compose -f docker-compose.integrationtest.yml down
  - mv tests/coverage.xml coverage.xml
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
