sudo: required

services:
  - docker

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - cp dataactcore/config_example.yml dataactcore/config.yml
  - cp dataactcore/local_config_example.yml dataactcore/local_config.yml
  - cp dataactcore/local_secrets_example.yml dataactcore/local_secrets.yml
  - pwd
  - ls -lath
  - |
    docker-compose run --rm dataact-broker \
      /bin/sh -c " \
      cd ./dataactcore; sleep 9s; alembic upgrade head; \
      cd ../; flake8 && echo 'hi' > tests/coverage.xml && echo 'hello' > .coverage && \
      #py.test --cov=. --cov-report xml:tests/coverage.xml --junitxml=tests/test-results.xml; \
      ls -lath"


after_script:
  - pwd
  - ls -lath
  - cat .coverage
  - ./cc-test-reporter after-build --coverage-input-type coverage.py --prefix tests --exit-code $TRAVIS_TEST_RESULT
    --debug tests/coverage.xml
  - docker-compose down

